services:
  - type: web
    name: vehicleverse
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --max-requests 50 --preload --worker-class sync
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: true
